### ISSUE TITLE
Make sure input and reference files are mounted to correct locations in containers

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/metadata-automation-challenge#16]
These are the main folder paths that should be available to participant tools (`input`, `output`, and `data`), where...

+ **`input`:** should include each of the four (currently) "testing" TSV input files and the "validation" input file for **Apollo5**
+ **`output`** should be a writable directory where the output of submitted tools are saved
+ **`data`** should include all *annotated* JSON files for challenge datasets, as well as any reference data files (e.g., the caDSR dump table)

![image](https://user-images.githubusercontent.com/5033229/71537225-c4009280-28cd-11ea-9677-d7b3313063d2.png)

**Note:** we may or may not want to use a separate directory (e.g., `user_data`) to store reference data that is generated by the participant's tool. Or... they can include that data at any point they want within their Docker image, as long as it doesn't collide with the three "protected" paths above.

**Comment by thomasyu888** [comment]
@jaeddy, will the participants be responsible for knowing the names of the `/input` files? If we just mounted each of these files as `dataset.tsv` then participants wouldn't need to switch the filenames when mounting different datasets?

Each model should produce a json file correct?  What should this json file be named? (It has have a specific name because of the CWL output binding)

**Comment by jaeddy** [comment]
@thomasyu888, I don't know that they necessarily need to be aware of the individual filenames in `/input`; however, if they're given a dataset name (e.g., `Apollo2`), their tool should be able to read in the data from `/input/<dataset_name>.tsv` (e.g., `/input/Apollo2.tsv`).

By extension, each tool should produce an output JSON file at `/output/Annotated-<dataset_name>.json` (e.g., `/output/Annotated-Apollo2.json`).

For our purposes, the possible values of `dataset_name` include:
+ "Apollo2"
+ "Outcome-Predictors"
+ "ROI-Masks"
+ "REMBRANDT"
+ "Apollo5"

If that sounds too confusing for participants, we can think of a different approach.

**Comment by jaeddy** [comment]
@thomasyu888 — OK to close this after #18?
