### ISSUE TITLE
Add functionality to compute score for entire column

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/metadata-automation-challenge#2]
Currently, scores are computed for each row, but we need to aggregate them in some way. I have a placeholder function (`get_col_score`) in `global.R`, but haven't attempted to get it working yet. Because submissions might not necessarily include the same number of results (for different columns and for different participants), we should aggregate using something like `max()` or `median()` to avoid size bias.

**Comment by thomasyu888** [comment]
Not quite understanding the bias portion.  Lets go through a couple examples:

A column with one result:
Result score: 3
Column score 3

A column with three results:
Result scores: 3, 0, 2
Column score: 3? or 2? (Is this what you mean by `max()` and `median()`)

**Comment by thomasyu888** [comment]
Add ability to choose max or median (Add toggle button on the left)
