### ISSUE TITLE
Update code and data on scoring instance with JSON schema fixes

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/metadata-automation-challenge#24]
Besides pulling down the latest version of `schema/output-schema.json`, we also need to sync changes made to `R/scoring.R`.

From Synapse, we should grab all of the `Annotated-<dataset_name>.json` files in the [`manually-curated_annotated` folder](https://www.synapse.org/#!Synapse:syn21088690).

**Comment by jaeddy** [comment]
Actually hold off on this for a bit. Making some additional changes. :)

**Comment by jaeddy** [comment]
OK — good now I think.

**Comment by thomasyu888** [comment]
Just so you know, we are working off of `dev`.  Will merge your updates in

**Comment by jaeddy** [comment]
Oh haha.. I didn't even notice there was a `dev` branch. Thanks!

**Comment by jaeddy** [comment]
Made one more (hopefully final) round of changes to schema stuff and synced everything in `dev`.
