### ISSUE TITLE
Create script/function to score entire submission file

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/metadata-automation-challenge#3]
In the `scoring_demo` app, there's a function (`get_res_score`) to compute the score for each result submitted for a column, and #2 will extend that to an aggregate score for each column. Eventually (for the scoring harness), we want to iterate over all columns and results to compute a combined score for the submission — but this should also be useful for the app, minimizing the number of runtime calculations.

**Comment by thomasyu888** [comment]
Sum of all the column scores / number of columns.
