### ISSUE TITLE
Connect match weighting/threshold parameters to scoring function

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/metadata-automation-challenge#4]
The function in #2 should be able to take inputs for the weightings and thresholds used to calculate scores for each check — either as individual arguments or as a single list/table. When the user updates the values for these parameters in the sidenav, we want some sort of button+`observe` combo to update scores.

**Comment by thomasyu888** [comment]
Should the overlap and coverage threshold be a slider between 0 to 1?
