### ISSUE TITLE
Send email communication with update to the participants

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/metadata-automation-challenge#69]
Send an email communication to participants with the following information (add as needed):

- The competitive phase of the challenge is extended (+ Round 3)
- Share submission video tutorial made @vpchung 

## Depends on

- #68

**Comment by tschaffter** [comment]
Assigning the ticket to myself while figuring out the GH username of Eric

**Comment by esotericglitch** [comment]
Hi Thomas,

Did I confirm your invite?

**Comment by tschaffter** [comment]
@esotericglitch Yes, I was able to successfully assign you to this ticket.

To clarify, are we going to send an email communication to participants soon? James sent one yesterday with the updated timeline. But we need to confirm to the participants if/when the second webinar will take place as well as where they can find additional resources for the challenge (video tutorial)?

**Comment by esotericglitch** [comment]
Sorry lost sight of this.  When would be a good date to hold the second webinar?

**Comment by esotericglitch** [comment]
Thanks for your feedback. Let's discuss today at 4PM or if its ready to go I'll send it out.
[doc](https://docs.google.com/document/d/1Hg25_YInePxdy5UO2PHYG2cwVjacPhWRWoXwL12yVng/edit?disco=AAAAJXl4JFc)

**Comment by tschaffter** [comment]
Eric sent the email last week
