### ISSUE TITLE
Double check the scores of the baseline method

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/metadata-automation-challenge#70]
@vpchung submitted the baseline method today to check that the pipeline is working well. I noticed that the performance for the dataset Outcome-Predictors is slightly different from the (same?) model submitted on Feb 24 (this looks actually like an old submission and since then we have updated the scoring script).

- [x] Submit the baseline model and check that we get the expected score
- [x] If the submission from Feb 24 has been made using the old scoring script, make this submission INVALID.
  - The score of this submission are up to date

**Comment by vpchung** [comment]
Just re-ran and got the same scores from the 14th -- we're good!
