### ISSUE TITLE
Fix Thesaurus file extension issue

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/metadata-automation-challenge#72]
A participant reported to Gilberto that the file `Thesaurus.tsv` is mounted as `Thesaurus.txt`. I guess the documentation may not be accurate. The participants said that this affected two of their submission.

- [ ] Figure out whether the issue is on the way the file is mounted or the documentation
- [ ] Tom reported that there may be a discrepancy in file version. Clarify with him and Denise/Gilberto
- [ ] Figure out how to compensate the team (CEDAR? to confirm). They may not be the only team that may have been affected so one solution could be to look at what other team have made submission in this round and give additional submission credits only to them.

**Comment by tschaffter** [comment]
@thomasyu888 and all: Can you list below all the occurrences of `Thesaurus.tsv` and `Thesaurus.txt` that you know of (documentation, workflow, github, etc.)?

**Comment by tschaffter** [comment]
- On the production site, Files > Data > reference > [Thesaurus.tsv](https://www.synapse.org/#!Synapse:syn21514905)

**Comment by thomasyu888** [comment]
@tschaffter. On the server, the file is named `Thesaurus.txt`.  Once I update this filename, it will be mounted into participant containers as `Thesaurus.tsv`.

That being said, will the older models submitted fail if people are using this file?

**Comment by tschaffter** [comment]
> That being said, will the older models submitted fail if people are using this file?

I still don't have a clear understanding of the issue. I think that we documented that the file has a `.tsv` extension while it is mounted as `.txt`. I have not seen the filename of this file being mentioned in the documentation. I have send an email to Gilberto and Denise.

**Comment by vpchung** [comment]
@tschaffter found one instance of `Thesaurus.txt` in the [Wiki](https://www.synapse.org/#!Synapse:syn18065891/wiki/600439) (under **2. Build your model** > Input files).

Perhaps at one point, it was `.txt`?

**Comment by tschaffter** [comment]
So we document this file as having the `.txt` extension and effectively mount it with `.tsv`. The confusion may actually arise from the fact that this file seems to be an older version of the `.tsv` file that is available under the Files section. The participant may be expecting this file but the file mounted does not match (either by its filename or by its content, that may have been updated since the txt version). Let's wait for Gilberto's reply.

**Comment by thomasyu888** [comment]
@tschaffter ,  I don't currently mount is as a `.tsv`.  I currently mount the file as a `.txt`.  That being said, while trying to figure out _why_ the file was named `.txt` instead of `.tsv`, I found the data difference.

**Comment by vpchung** [comment]
Fix: mounted the latest Thesaurus file as both a .txt and .tsv in the infra
